branches:
  only:
    - /master.*/
    - /develop.*/
    - /feature\/.*/
language: cpp
script:
  - pushd src/engine
  - export CXX=${TRAVIS_COMPILER}
  - ./build.sh ${TOOLSET}
  - popd
  - pushd test
  - python test_all.py ${TOOLSET}
  - popd
  - src/engine/b2 --prefix=${HOME}/b2 install
  - ls -laFR ${HOME}/b2
stages:
  - name: test
  - name: website update
    if: branch IN (develop,master) AND type IN (push)
jobs:
  include:
    - env: TOOLSET=gcc
      os: linux
      compiler: g++-4.7
      addons:
        apt:
          packages:
            - g++-4.7
          sources:
            - ubuntu-toolchain-r-test
    - env: TOOLSET=gcc
      os: linux
      compiler: g++-4.8
      addons:
        apt:
          packages:
            - g++-4.8
          sources:
            - ubuntu-toolchain-r-test
    - env: TOOLSET=gcc
      os: linux
      compiler: g++-4.9
      addons:
        apt:
          packages:
            - g++-4.9
          sources:
            - ubuntu-toolchain-r-test
    - env: TOOLSET=gcc
      os: linux
      compiler: g++-5
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
    - env: TOOLSET=gcc
      os: linux
      compiler: g++-6
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
    - env: TOOLSET=gcc
      os: linux
      compiler: g++-7
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
    - env: TOOLSET=gcc
      os: linux
      compiler: g++-8
      addons:
        apt:
          packages:
            - g++-8
          sources:
            - ubuntu-toolchain-r-test
    - env: TOOLSET=clang
      os: linux
      compiler: /usr/bin/clang++
      addons:
        apt:
          packages:
            - clang-3.3
            - llvm-3.3-dev
    - env: TOOLSET=clang
      os: linux
      compiler: /usr/bin/clang++
      addons:
        apt:
          packages:
            - clang-3.4
            - llvm-3.4-dev
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-3.5
      addons:
        apt:
          packages:
            - clang-3.5
            - llvm-3.5-dev
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.5
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-3.6
      addons:
        apt:
          packages:
            - clang-3.6
            - llvm-3.6-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-3.7
      addons:
        apt:
          packages:
            - clang-3.7
            - llvm-3.7-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - llvm-3.8-dev
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.8
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-3.9
      addons:
        apt:
          packages:
            - clang-3.9
            - llvm-3.9-dev
            - libstdc++-4.9-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.9
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-4.0
      addons:
        apt:
          packages:
            - clang-4.0
            - llvm-4.0-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-5.0
      addons:
        apt:
          packages:
            - clang-5.0
            - llvm-5.0-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-6.0
      addons:
        apt:
          packages:
            - clang-6.0
            - llvm-6.0-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-6.0
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-7
      addons:
        apt:
          packages:
            - clang-7
            - llvm-7-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
    - env: TOOLSET=clang
      os: linux
      compiler: clang++-8
      addons:
        apt:
          packages:
            - clang-8
            - llvm-8-dev
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
    - os: osx
      osx_image: xcode10
      env: TOOLSET=clang
      compiler: clang
    - os: osx
      osx_image: xcode9.4
      env: TOOLSET=clang
      compiler: clang
    - os: osx
      osx_image: xcode9.3
      env: TOOLSET=clang
      compiler: clang
    - os: osx
      osx_image: xcode9.2
      env: TOOLSET=clang
      compiler: clang
    - os: osx
      osx_image: xcode9.1
      env: TOOLSET=clang
      compiler: clang
    - os: osx
      osx_image: xcode9
      env: TOOLSET=clang
      compiler: clang
    - os: osx
      osx_image: xcode8.3
      env: TOOLSET=clang
      compiler: clang
    - os: osx
      osx_image: xcode8
      env: TOOLSET=clang
      compiler: clang
    - os: osx
      osx_image: xcode7.3
      env: TOOLSET=clang
      compiler: clang
    - stage: website update
      os: linux
      script:
        - gem install asciidoctor
        - gem install pygments.rb
        - pip install --user Pygments
        - pip install --user https://github.com/bfgroup/jam_pygments/archive/master.zip
        - git config user.email "b2-bot"
        - git config user.name "b2-bot"
        - echo "using asciidoctor ;" >> project-config.jam
        - pushd src/engine
        - ./build.sh
        - popd
        - ./bootstrap.sh --with-toolset=${TOOLSET}
        - pushd doc
        - ../b2 --website-doc-dir=manual/${TRAVIS_BRANCH} website