sudo: false
branches:
  only:
    - master
    - develop
    - /feature\/.*/
language: cpp
install:
  - gem install asciidoctor
  - gem install pygments.rb
  - pip install --user Pygments
script:
  - pushd src/engine
  - ./build.sh
  - popd
  - ./bootstrap.sh --with-toolset=${TOOLSET}
  - pushd test
  - python test_all.py ${TOOLSET}
  - popd
stages:
  - name: test
  - name: website update
    if: branch IN (feature/new-doc-format,develop)
jobs:
  include:
    - os: linux
      dist: trusty
      env: TOOLSET=gcc
    - os: linux
      dist: trusty
      env: TOOLSET=clang
    - os: linux
      dist: precise
      env: TOOLSET=gcc
      if: NOT branch IN (feature/new-doc-format)
    - os: linux
      dist: precise
      env: TOOLSET=clang
      if: NOT branch IN (feature/new-doc-format)
    - os: osx
      osx_image: xcode9.2
      env: TOOLSET=clang
      if: NOT branch IN (feature/new-doc-format)
    - os: osx
      osx_image: xcode9.1
      env: TOOLSET=clang
      if: NOT branch IN (feature/new-doc-format)
    - os: osx
      osx_image: xcode9
      env: TOOLSET=clang
      if: NOT branch IN (feature/new-doc-format)
    - os: osx
      osx_image: xcode8.3
      env: TOOLSET=clang
      if: NOT branch IN (feature/new-doc-format)
    - os: osx
      osx_image: xcode8
      env: TOOLSET=clang
      if: NOT branch IN (feature/new-doc-format)
    - os: osx
      osx_image: xcode7.3
      env: TOOLSET=clang
      if: NOT branch IN (feature/new-doc-format)
    - os: osx
      osx_image: xcode6.4
      env: TOOLSET=clang
      if: NOT branch IN (feature/new-doc-format)
    - stage: website update
      os: linux
      script:
        - git config user.email "b2-bot"
        - git config user.name "b2-bot"
        - echo "using asciidoctor ;" >> project-config.jam
        - pushd src/engine
        - ./build.sh
        - popd
        - ./bootstrap.sh --with-toolset=${TOOLSET}
        - pushd doc
        - ../b2 --website-doc-dir=manual/develop website
