sudo: false
os:
  - linux
  - osx
env:
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true
matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - os: linux
      dist: trusty
      env: TOOLSET=gcc
    - os: linux
      dist: trusty
      env: TOOLSET=clang
    - os: osx
      osx_image: xcode8.3
      env: TOOLSET=clang
language: cpp
script:
  - cd src/engine
  - ./build.sh
  - cd ../..
  - ./bootstrap.sh --with-toolset=${TOOLSET}
  - cd test
  - python test_all.py ${TOOLSET}
