sudo: false
branches:
  only:
    - master
    - develop
    - /feature\/.*/
language: cpp
test: &test
  script:
    - pushd src/engine
    - ./build.sh
    - popd
    - ./bootstrap.sh --with-toolset=${TOOLSET}
    - pushd test
    - python test_all.py ${TOOLSET}
    - popd
stages:
  - name: test
  - name: website update
    if: branch IN (feature/new-doc-format,develop)
job:
  include:
    - <<: *test
      os: linux
      dist: precise
      env: TOOLSET=gcc
    - <<: *test
      os: linux
      dist: precise
      env: TOOLSET=clang
    - <<: *test
      os: linux
      dist: trusty
      env: TOOLSET=gcc
    - <<: *test
      os: linux
      dist: trusty
      env: TOOLSET=clang
    - <<: *test
      os: osx
      osx_image: xcode9.2
      env: TOOLSET=clang
    - <<: *test
      os: osx
      osx_image: xcode9.1
      env: TOOLSET=clang
    - <<: *test
      os: osx
      osx_image: xcode9
      env: TOOLSET=clang
    - <<: *test
      os: osx
      osx_image: xcode8.3
      env: TOOLSET=clang
    - <<: *test
      os: osx
      osx_image: xcode8
      env: TOOLSET=clang
    - <<: *test
      os: osx
      osx_image: xcode7.3
      env: TOOLSET=clang
    - <<: *test
      os: osx
      osx_image: xcode6.4
      env: TOOLSET=clang
    - stage: website update
      os: linux
      script:
        - git config user.email "b2-bot"
        - git config user.name "b2-bot"
        - pushd src/engine
        - ./build.sh
        - popd
        - ./bootstrap.sh --with-toolset=${TOOLSET}
        - pushd doc
        - ../b2 --website-doc-dir=manual/develop website
