sudo: false
env:
  matrix:
    - TRAVIS_EMPTY_JOB_WORKAROUND=true
matrix:
  exclude:
    - env: TRAVIS_EMPTY_JOB_WORKAROUND=true
  include:
    - os: linux
      dist: trusty
      env: TOOLSET=gcc TEST_ALL_EXTRAS=
    - os: linux
      dist: precise
      env: TOOLSET=clang TEST_ALL_EXTRAS=
    - os: osx
      osx_image: xcode8.3
      env: TOOLSET=clang TEST_ALL_EXTRAS=
language: python
script:
  - ./bootstrap.sh --with-toolset=${TOOLSET}
  - cd test && DO_DIFF=1 python test_all.py ${TOOLSET} ${TEST_ALL_EXTRAS}
