# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2015-2017.

 
image:
  - Visual Studio 2017
  - Visual Studio 2015
  - Visual Studio 2013

environment:
  matrix:
  - TEST_ALL_EXTRAS:

build_script:
- ps: |
    & .\bootstrap.bat
    $BootstrapExitCode = $LastExitCode
    if (Test-Path bootstrap.log)
    {
        Push-AppveyorArtifact bootstrap.log
    }
    if ($BootstrapExitCode -ne 0) { $host.SetShouldExit($BootstrapExitCode) }

test_script:
- ps: |
    cd test
    & python test_all.py msvc $env:TEST_ALL_EXTRAS --preserve
    $TestExitCode = $LastExitCode
    if (Test-Path failed_test)
    {
        & 7z a failed_test.zip failed_test\*
        Push-AppveyorArtifact failed_test.zip
    }
    if ($TestExitCode -ne 0) { $host.SetShouldExit($TestExitCode) }
