# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2015-2017.

branches:
  only:
    - /master.*/
    - /develop.*/
    - /feature\/.*/
 
environment:
  TEST_ALL_EXTRAS:
  matrix:
  - TOOLSET: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
  - TOOLSET: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: msvc
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
  - TOOLSET: mingw
    CXX: C:\MinGW\bin\g++.exe
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: mingw
    CXX: C:\mingw-w64\i686-5.3.0-posix-dwarf-rt_v4-rev0\mingw64\bin\g++.exe
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: mingw
    CXX: C:\mingw-w64\x86_64-6.3.0-posix-seh-rt_v5-rev1\mingw64\bin\g++.exe
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: mingw
    CXX: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin\g++.exe
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
  - TOOLSET: mingw
    CXX: C:\mingw-w64\x86_64-7.3.0-posix-seh-rt_v5-rev0\mingw64\bin\g++.exe
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015

build_script:
  - cd src/engine
  - build.bat %TOOLSET%
  - cd ../..

test_script:
  - cd test
  - python test_all.py msvc
  - cd ..

after_test:
  - src\engine\b2.exe --prefix=%HOME%/b2 install
