# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2015-2019.

jobs:
- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      GCC:
        TOOLSET: gcc
        TEST_TOOLSET: gcc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
      addToPath: true
  - displayName: Install
    bash: |
        uname -a
        which g++
        which clang++
  - displayName: Build
    bash: |
        cd src/engine
        set PATH=${PATH};${CXX_PATH}
        ./build.sh ${TOOLSET}
        cd ../..
  - displayName: Test
    bash: |
        cd test
        echo "using ${TEST_TOOLSET} : : ${CXX} ;" > ${HOME}/user-config.jam
        python test_all.py ${TEST_TOOLSET}
        cd ..
- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      MSVC:
        TOOLSET: msvc
        TEST_TOOLSET: msvc
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
      addToPath: true
  - displayName: Build
    powershell: |
        cd src/engine
        $env:path += ';' + $env:CXX_PATH
        build.bat $env:TOOLSET
        cd ../..
  - displayName: Test
    powershell: |
        cd test
        echo "using" $env:TEST_TOOLSET ":" ":" $env:CXX ";" > $env:HOME/user-config.jam
        python test_all.py $env:TEST_TOOLSET
        cd ..
