# Use, modification, and distribution are
# subject to the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
#
# Copyright Rene Rivera 2015-2019.

trigger:
- feature/cxx

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      GCC 8.0:
        TOOLSET: gcc
        TEST_TOOLSET: gcc
        CXX: g++-8
        PACKAGES: g++-8
  steps:
  - bash: |
        set -e
        uname -a
        sudo -E apt-add-repository -y "ppa:ubuntu-toolchain-r/test"
        sudo -E apt-get -yq --no-install-suggests --no-install-recommends install ${PACKAGES}
    displayName: Install
  - bash: |
        set -e
        cd src/engine
        set PATH=${PATH};${CXX_PATH}
        ./build.sh ${TOOLSET}
        cd ../..
    displayName: Build
  - bash: |
        set -e
        CXX_PATH=`which ${CXX}`
        cd test
        echo "using ${TEST_TOOLSET} : : ${CXX_PATH} ;" > ${HOME}/user-config.jam
        python test_all.py ${TEST_TOOLSET}
        cd ..
    displayName: Test

- job: 'Windows'
  strategy:
    matrix:
      VS 2017:
        TOOLSET: vc141
        TEST_TOOLSET: msvc
        VM_IMAGE: 'vs2017-win2016'
      VS 2015:
        TOOLSET: vc140
        TEST_TOOLSET: msvc
        VM_IMAGE: 'vs2015-win2012r2'
      VS 2013:
        TOOLSET: vc12
        TEST_TOOLSET: msvc
        VM_IMAGE: 'vs2015-win2012r2'
  pool:
    vmImage: $(VM_IMAGE)
  steps:
  - powershell: |
        cd src/engine
        $env:path += ';' + $env:CXX_PATH
        cmd /c build.bat $env:TOOLSET
        cd ../..
    displayName: Build
  - powershell: |
        cd test
        echo "using" $env:TEST_TOOLSET ":" ":" $env:CXX ";" > $env:HOME/user-config.jam
        python test_all.py $env:TEST_TOOLSET
        cd ..
    displayName: Test

- job: 'macOS'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Xcode 10.1:
        TOOLSET: clang
        TEST_TOOLSET: clang
        CXX: clang++
        XCODE_APP: /Applications/Xcode_10.1.app
  steps:
  - bash: |
        set -e
        uname -a
        sudo xcode-select -switch ${XCODE_APP}
        which clang++
    displayName: Install
  - bash: |
        set -e
        cd src/engine
        ./build.sh ${TOOLSET}
        cd ../..
    displayName: Build
  - bash: |
        set -e
        CXX_PATH=`which ${CXX}`
        cd test
        echo "using ${TEST_TOOLSET} : : ${CXX_PATH} ;" > ${HOME}/user-config.jam
        python test_all.py ${TEST_TOOLSET}
        cd ..
    displayName: Test
